In [4]:
import torch
import numpy as np

In [11]:
x_np = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(x_np)
x_np = np.reshape(x_np, (4,2), order = 'F')
print(x_np)
x = torch.tensor(np.array([1, 2, 3, 4, 5, 6, 7, 8]))
print(x)
x = x.reshape(-1,4,2)
print(x)

[1 2 3 4 5 6 7 8]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]])


In [42]:
import cv2

test = cv2.imread('../Data/SyntheticTrain/patch_A/1.jpg', cv2.IMREAD_GRAYSCALE)
# print(test)
print(test.shape)
print(test)
patch_A = np.expand_dims(test, 2)
print(patch_A.shape)
print(patch_A)

# patch_A = torch.tensor(patch_A).permute(2, 0, 1)
# print(patch_A.shape)
# print(patch_A)
patch_A = np.squeeze(patch_A)
patch_A = np.expand_dims(patch_A, axis=0)
print(patch_A.shape)
print(patch_A)

patch_B = np.expand_dims(test, 1)

# Pa_Pb = np.concatenate((patch_A, patch_B), axis = 2)

# print(Pa_Pb)

(128, 128)
[[151 155 126 ...  81  78  78]
 [156 155 145 ...  81  80  85]
 [154 157 155 ...  87  82  80]
 ...
 [ 41  41  42 ...  42  41  40]
 [ 39  39  39 ...  41  42  39]
 [ 38  37  36 ...  41  42  39]]
(1, 128, 128)
[[[151 155 126 ...  81  78  78]
  [156 155 145 ...  81  80  85]
  [154 157 155 ...  87  82  80]
  ...
  [ 41  41  42 ...  42  41  40]
  [ 39  39  39 ...  41  42  39]
  [ 38  37  36 ...  41  42  39]]]
